-- Create the products table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL CHECK (price > 0),
  quantity INTEGER NOT NULL DEFAULT 0 CHECK (quantity >= 0),
  category TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Insert some sample data
INSERT INTO products (name, description, price, quantity, category)
VALUES 
  ('Laptop', 'High-performance laptop', 999.99, 10, 'Electronics'),
  ('Coffee Mug', 'Ceramic coffee mug', 12.50, 50, 'Kitchenware');
